[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]
broadcast = "./broadcast"
fs_permissions = [ {access = "read", path="./broadcast"} ]